<?php

namespace OTGH\AccessControl\Core\Services\Supervisor;

use Illuminate\Support\Facades\File;
use OTGH\AccessControl\Core\Services\AccessControl\AccessControlSettingsRepository;
use Symfony\Component\Process\Process;

class AccessControlSupervisorConfigManager
{
    public function __construct(
        private readonly SupervisorProgramRegistry $programRegistry,
        private readonly AccessControlSettingsRepository $settings,
    ) {}

    public function rebuild(?string $outputPath = null): string
    {
        $path = $outputPath ?: $this->defaultOutputPath();
        $content = $this->render();

        File::ensureDirectoryExists((string) dirname($path));
        File::put($path, $content);

        return $path;
    }

    public function render(): string
    {
        $workingDir = base_path();
        $phpBinary = PHP_BINARY;

        $sections = [
            $this->header($workingDir),
            $this->queueProgram($phpBinary, $workingDir),
            $this->mqttMonitorProgram($phpBinary, $workingDir),
        ];

        foreach ($this->programRegistry->renderSections($phpBinary, $workingDir) as $section) {
            $sections[] = $section;
        }

        return implode("\n\n", $sections)."\n";
    }

    public function defaultOutputPath(): string
    {
        return (string) env('ACCESS_CONTROL_SUPERVISOR_CONFIG_PATH', base_path('deploy/supervisor/access-control.conf'));
    }

    /**
     * @return array{ok:bool,steps:array<int,array{command:string,ok:bool,output:string,exit_code:int}>}
     */
    public function applySupervisorChanges(): array
    {
        $commands = $this->supervisorApplyCommands();
        $steps = [];
        $allOk = true;

        foreach ($commands as $command) {
            $process = Process::fromShellCommandline($command, base_path());
            $process->setTimeout($this->supervisorCommandTimeoutSeconds());
            $process->run();

            $ok = $process->isSuccessful();
            if (! $ok) {
                $allOk = false;
            }

            $steps[] = [
                'command' => $command,
                'ok' => $ok,
                'output' => trim($process->getOutput()."\n".$process->getErrorOutput()),
                'exit_code' => $process->getExitCode() ?? 1,
            ];

            if (! $ok && $this->supervisorFailFast()) {
                break;
            }
        }

        return [
            'ok' => $allOk,
            'steps' => $steps,
        ];
    }

    private function header(string $workingDir): string
    {
        $configPath = $this->defaultOutputPath();

        return <<<CONF
; Supervisor programs for access-control app queue + MQTT monitor
;
; Auto-generated by: php artisan app:rebuild-access-control-supervisor
; Install steps (as root):
;   ln -sfn {$configPath} /etc/supervisor/conf.d/access-control.conf
;   supervisorctl reread
;   supervisorctl update
;   supervisorctl status
CONF;
    }

    private function queueProgram(string $phpBinary, string $workingDir): string
    {
        return <<<CONF
[program:access-control-queue]
command={$phpBinary} {$workingDir}/artisan queue:work redis --queue=default --sleep=1 --tries=3 --max-time=3600 --timeout=120
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
user=www-data
directory={$workingDir}
redirect_stderr=true
stdout_logfile={$workingDir}/storage/logs/supervisor-queue.log
stopwaitsecs=3600
CONF;
    }

    private function mqttMonitorProgram(string $phpBinary, string $workingDir): string
    {
        return <<<CONF
[program:access-control-mqtt-monitor]
command={$phpBinary} {$workingDir}/artisan app:monitor-device-mqtt-commands --connection=monitor --qos=0
autostart=true
autorestart=true
startsecs=2
startretries=10
user=www-data
directory={$workingDir}
redirect_stderr=true
stdout_logfile={$workingDir}/storage/logs/supervisor-mqtt-monitor.log
stopasgroup=true
killasgroup=true
stopwaitsecs=30
CONF;
    }

    /**
     * @return array<int,string>
     */
    private function supervisorApplyCommands(): array
    {
        $configured = $this->settings->get('supervisor.apply_commands', [
            'sudo -n supervisorctl reread',
            'sudo -n supervisorctl update',
        ]);

        if (! is_array($configured)) {
            return [];
        }

        return array_values(array_filter(array_map(
            static fn (mixed $command): string => is_scalar($command) ? trim((string) $command) : '',
            $configured
        ), static fn (string $command): bool => $command !== ''));
    }

    private function supervisorCommandTimeoutSeconds(): float
    {
        return max(1.0, (float) $this->settings->get('supervisor.command_timeout_seconds', 30));
    }

    private function supervisorFailFast(): bool
    {
        return (bool) $this->settings->get('supervisor.fail_fast', true);
    }
}
